[package]
name = "PastePrime"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
enigo = "0.3.0"
global-hotkey = "0.6.4"
trayicon = "0.2.0"
winit = "0.30.9"
auto-launch = "0.5.0"

[build-dependencies]
winresource = "0.1.20"
